name: release

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_NOA: noa
  IMAGE_NAME_LL: lavalink

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build-publish-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY -u ${{ github.actor }} --password-stdin

      - name: Build noa image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME_NOA --label "runnumber=${GITHUB_RUN_ID}"

      - name: Push noa image
        run: |
          IMAGE_ID=$REGISTRY/${{ github.repository_owner }}/$IMAGE_NAME_NOA

          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME_NOA $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      - name: Build lavalink image
        run: docker build lavalink/. --file lavalink/Dockerfile --tag $IMAGE_NAME_LL --label "runnumber=${GITHUB_RUN_ID}"

      - name: Push lavalink image
        run: |
          IMAGE_ID=$REGISTRY/${{ github.repository_owner }}/$IMAGE_NAME_NOA/$IMAGE_NAME_LL

          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME_LL $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
